---
title: STAT 548 PhD Qualifying Papers (2024 - 2025)
author: ypp
date: "2024-09-01"
---

## Introduction

I am interested in almost all problems in computational biology and
genomics. I expect a student to propose novel statistical approaches
that can address challenges in data analysis and modelling of
high-dimensional, large-volume biological problems. In many cases, I
can provide relevant data sets and help students find collaborators to
facilitate publications in a biological venue. Feel free to contact me
(`ypp@stat.ubc.ca`).

## An expected format for the report

You may organize your report including the following sections.

- **Problem definition** (1 page): Extract mathematical/statistical problems from the paper and organize them. What are the input data? What is the expected output?

- **Significance** (1-2 paragraphs): Why is this an interesting problem? What can be learned by studying this problem? Why is it exciting for you? Author contribution: How did the author(s) find the solution? What was a novel contribution beyond traditional approaches?

- **Limitations/challenges** (1-2 paragraphs): What are the assumptions? Are they realistic? What are the technical limitations that the authors acknowledge or not?

- **Novel idea/methods** (2 pages): Propose your idea and statistical methods. You could interpret the underlying problem in a different formulation. What are related problems/frameworks, but not adopted by the authors?

- **Results** (1-2 pages): Include one figure that sketches your approaches. Show tables and figures that clearly demonstrate your methods.

- **Discussion** (1 page): Briefly discuss what you have learned and what you would achieve if you were to develop this to a full paper. How would you validate your findings in independent studies, including wet-lab experiments?


## Available Papers

1. Wang, Sarkar, Carbonetto, and Stephens, [A simple new approach to variable selection in regression, with application to genetic fine mapping](https://rss.onlinelibrary.wiley.com/doi/10.1111/rssb.12388), 2020

    * Reference site [SuSiE](https://stephenslab.github.io/susie-paper/)
	
    * **Idea**: There is room for improvements in their Bayes factor calculation. Can we replace Gaussian Single Effect Regression with t-distributed SER?

