---
title: STAT 548 PhD Qualifying Papers
author: ypp
date: "`r Sys.Date()`"
---


## Introduction

I am interested in almost all problems in computational biology and genomics. I expect a student to propose novel statistical approaches that can address challenges in data analysis and modelling of high-dimensional, large-volume biological problems. In many cases, I can provide relevant data sets and help students find collaborators to facilitate publications in a biological venue. Feel free to contact me (`ypp@stat.ubc.ca`).

## An expected format for the report

You may organize your report including the following sections.

- **Problem definition** (1 page): Extract mathematical/statistical problems from the paper and organize them. What are the input data? What is the expected output?

- **Significance** (1-2 paragraphs): Why is this an interesting problem? What can be learned by studying this problem? Why is it exciting for you? Author contribution: How did the author(s) find the solution? What was a novel contribution beyond traditional approaches?

- **Limitations/challenges** (1-2 paragraphs): What are the assumptions? Are they realistic? What are the technical limitations that the authors acknowledge or not?

- **Novel idea/methods** (2 pages): Propose your idea and statistical methods. You could interpret the underlying problem in a different formulation. What are related problems/frameworks, but not adopted by the authors?

- **Results** (1-2 pages): Include one figure that sketches your approaches. Show tables and figures that clearly demonstrate your methods.

- **Discussion** (1 page): Briefly discuss what you have learned and what you would achieve if you were to develop this to a full paper. How would you validate your findings in independent studies, including wet-lab experiments?



## Available Papers

1. Abadie and Imbens, [Large sample properties of matching estimators for average treatment effects](https://doi.org/10.1111/j.1468-0262.2006.00655.x), Econometrica (2005)

	* **Category**: causal inference, single-cell genomics

	* **Idea**: Extending the basic idea of this paper, implement a matching-based counterfactual inference method to adjust unknown covariates to estimate causal effects. Test your methods for (causally-) differential expression analysis on simulated/real-world single-cell RNA-seq data. You may also propose novel data normalization, confounder-correction methods that clearly hinge on the notion of causality.

2. Hill, [Bayesian Nonparametric Modeling for Causal Inference](https://www.tandfonline.com/doi/abs/10.1198/jcgs.2010.08162) (2012); Louizos _et al._ [Causal Effect Inference with Deep Latent-Variable Models](http://papers.nips.cc/paper/7223-causal-effect-inference-with-deep-latent-variable-models) (2017)

	* **Category**: causal inference, Bayesian inference

	* **Idea**: Using counterfactual data modelling/sampling, we can train a model that captures latent representation of confounding factors. Can we combine the idea of a counterfactual model with stochastic variational inference that consumes stochastically-generated minibatch data to update parameters in each epoch? If so, what is optimal sampling strategy to feed in counterfactual data to the inference engine?

3. Murray, Adams, and MacKay, [Elliptical slice sampling](http://proceedings.mlr.press/v9/murray10a.html) (2010)

	* **Category**: Bayesian inference, cell type deconvolution

	* **Idea**: Multiple directions are possible. (1) Revisit optimization-based non-conjugate, non-analytical models such as this [cell type deconvolution model](https://www.nature.com/articles/s41467-018-08023-x) and quantify the level of uncertainty using ESS. Test on simulated data, varying the number of putative cell types and the gap between rare and abundant cell types. (2) Another interesting direction can be an application to black-box stochastic variation inference. You may design and demonstrate a novel stochastic gradient estimation method that can better handle a high-dimensional parametric model than a basic approach.


4. Zhu and Stephens, [Bayesian large-scale multiple regression with summary statistics from genome-wide association studies](https://projecteuclid.org/euclid.aoas/1507168840) (2017)

   * **Category**: statistical genetics, summary statistics-based inference. 

   * **Idea**: Multiple directions are possible. (1) A new model that allows multiple types of summary statistics matrix. (2) A new inference method that takes advantage of both partially-observed individual-level and summary statistics data. (3) Built on this framework, you may formulate [stratified LD-score regression model](https://www.nature.com/articles/ng.3404) with (Bayesian) sparse prior. (4) Show correspondence with existing polygenic risk prediction methods.

5. Ryder _et al._, [Black-box variational inference for stochastic differential equations](https://arxiv.org/abs/1802.03335) 

   * **Category**: single-cell genomics, dynamics, variational inference

   * **Idea**: Propose a likelihood-free inference method for the ordinary differential equation (ODE) model used in Bergen _et al._, [Generalizing RNA velocity to transient cell states through dynamical modeling](https://www.nature.com/articles/s41587-020-0591-3). You are welcomed to extend the gene-by-gene ODE model to a finite (or infinite) mixture of ODE models. You may like to read [Rasmussen and Ghahramani](http://papers.nips.cc/paper/2055-infinite-mixtures-of-gaussian-process-experts.pdf) for this. Alternatively, you can design spatiotemporal partial differential equations and estimate posterior distributions of the parameters by the black-box inference algorithm. We can then apply your method to spatial transcriptomic data, such as [Integrating microarray-based spatial transcriptomics and single-cell RNA-seq reveals tissue architecture in pancreatic ductal adenocarcinomas](https://www.nature.com/articles/s41587-019-0392-8).

